### ISSUE TITLE
Is there any plan to support the new module loading system in Python 3?

### ISSUE THREAD

**Issue by dmick** [pecan/pecan#157]
https://github.com/ceph/chacra uses Pecan's 'from pecan.ext' importer override.  This mechanism is broken with Python3 (not sure exactly where, but at least 3.12 has started to require a "find_spec()" entry point in the sys.meta_path importer, and I think also a loader() entry point but I have not studied it).

Are there any plans to make extension loading work with newer Python versions?

**Comment by ryanpetrello** [comment]
Hey Dan,

There's not a lot of proactive development on pecan these days, but if you could give me some instructions on a reproducer or a traceback you're seeing, I could take a look and gauge the effort necessary to support whatever's changed in Python 3.12.

Hope you're well!

**Comment by ryanpetrello** [comment]
Or you could try bullying @alfredodeza into fixing it.

😄

**Comment by dmick** [comment]
Where I experienced this was trying to run a database-populate command on a new chacra deployment, basically the first exercise of the new code during a deployment.  The import extension tries to redirect "import pecan.ext.notario" into a separate project tree for notario (to accomplish out-of-tree plugin addition), and fails because the import extension isn't called with the same protocol.  Reproducing it *may* be tricky; this was inside a pile of ansible to do the deploy and there's a lot of app setup to figure out.  Maybe it's not intractable but it's probably a bit ugly for you to try.

Really I just wanted to start by making initial contact.

That said, here's the traceback (inside the ansible invocation that caused it); it's just an import failure because the import extension mechanism didn't do its job:

```fatal: [chacra-do1.ceph.com]: FAILED! => changed=true
  cmd:
  - /opt/chacra/bin/pecan
  - populate
  - /opt/chacra/src/chacra/prod.py
  delta: '0:00:01.535826'
  end: '2025-01-21 19:07:45.452641'
  msg: non-zero return code
  rc: 1
  start: '2025-01-21 19:07:43.916815'
  stderr: |-
    Traceback (most recent call last):
      File "/opt/chacra/bin/pecan", line 8, in <module>
        sys.exit(CommandRunner.handle_command_line())
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/opt/chacra/lib/python3.12/site-packages/pecan/commands/base.py", line 97, in handle_command_line
        runner.run(sys.argv[1:])
      File "/opt/chacra/lib/python3.12/site-packages/pecan/commands/base.py", line 92, in run
        self.commands[ns.command_name]().run(ns)
      File "/opt/chacra/src/chacra/chacra/commands/populate.py", line 34, in run
        self.load_app()
      File "/opt/chacra/lib/python3.12/site-packages/pecan/commands/base.py", line 163, in load_app
        return load_app(self.args.config_file)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/opt/chacra/lib/python3.12/site-packages/pecan/core.py", line 202, in load_app
        set_config(config, overwrite=True)
      File "/opt/chacra/lib/python3.12/site-packages/pecan/configuration.py", line 240, in set_config
        config = conf_from_file(config)
                 ^^^^^^^^^^^^^^^^^^^^^^
      File "/opt/chacra/lib/python3.12/site-packages/pecan/configuration.py", line 171, in conf_from_file
        SourceFileLoader(module_name, abspath).load_module(module_name)
      File "<frozen importlib._bootstrap_external>", line 649, in _check_name_wrapper
      File "<frozen importlib._bootstrap_external>", line 1176, in load_module
      File "<frozen importlib._bootstrap_external>", line 1000, in load_module
      File "<frozen importlib._bootstrap>", line 537, in _load_module_shim
      File "<frozen importlib._bootstrap>", line 966, in _load
      File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
      File "<frozen importlib._bootstrap_external>", line 995, in exec_module
      File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
      File "/opt/chacra/src/chacra/prod.py", line 5, in <module>
        from prod_db import sqlalchemy
    ModuleNotFoundError: No module named 'prod_db'
  stderr_lines: <omitted>
  stdout: ==> LOADING ENVIRONMENT
  stdout_lines: <omitted>```

**Comment by ryanpetrello** [comment]
I'll take some time this next week or two to see if I can reproduce something like this in 3.12.  Admittedly it's pretty new and the `.ext` stuff is a fairly esoteric feature in pecan.

I'll let you know what I find.

**Comment by ryanpetrello** [comment]
Here's a reproducer:

```
~/venvs/tmp-4e8f237e3b54f5b/example cat setup.py
from setuptools import setup, find_packages
import re


module_file = open("pecan_example/__init__.py").read()

requirements = ['pecan']

setup(
    name='pecan-example',
    version=1.0,
    description="""
    """,
    long_description=None,
    classifiers=[
        'Development Status :: 5 - Production/Stable',
        'Intended Audience :: Developers',
        'Intended Audience :: System Administrators',
        'License :: OSI Approved :: BSD License',
        'Operating System :: MacOS :: MacOS X',
        'Operating System :: POSIX',
        'Programming Language :: Python'
    ],
    install_requires=requirements,
    zip_safe=False,
    packages=find_packages(exclude=['ez_setup']),
    entry_points="""
    [pecan.extension]
    example = pecan_example
    """
)

~/venvs/tmp-4e8f237e3b54f5b/example cat pecan_example/__init__.py
print("IMPORTED!")

def foo():
    print('bar')
```

```
>>> from pecan.ext import example
IMPORTED!
>>> example.foo
<function foo at 0x103856670>
>>> example.foo()
bar```

Works in Python3.9.

Does *not* work in Python3.12:

```
/venvs/tmp-98d3a809e91ee53/example python
Python 3.12.6 (main, Sep  6 2024, 19:03:47) [Clang 15.0.0 (clang-1500.3.9.4)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
Could not open PYTHONSTARTUP
FileNotFoundError: [Errno 2] No such file or directory: '/Users/rpetrello/.pythonrc'
>>> from pecan.ext import example
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'example' from 'pecan.ext' (/Users/rpetrello/venvs/tmp-98d3a809e91ee53/pecan/pecan/ext/__init__.py)
```

**Comment by ryanpetrello** [comment]
@dmick any way you could help me validate this patch?

https://github.com/pecan/pecan/pull/158

**Comment by dmick** [comment]
Testing the current version, which calls "load_module()", it sppears to work on the first import encountered (python.ext.notario) but fails on the second one which does not begin with pecan.ext.  In the original code, find_module() would exit if the path didn't start with pecan.ext.

When trying to change that by calling find_module() instead of load_module(), now the error is
```
      File "/opt/chacra/src/chacra/chacra/controllers/repos/__init__.py", line 7, in <module>
        from pecan.ext.notario import validate
      File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
      File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
      File "<frozen importlib._bootstrap>", line 913, in _load_unlocked
    AttributeError: 'PecanExtensionImporter' object has no attribute 'loader'
```

**Comment by dmick** [comment]
I still don't know what I'm talking about, but, reading further in PEP451, it seems like find_spec() wants to actually return a ModuleSpec, which it might be able to do with spec_from_loader() (?)

**Comment by dmick** [comment]
Well, with the fix as written in your PR, pecan.ext.notario seems to work, but brotlicffi is what ends up with 
```
     File "/opt/chacra/lib/python3.12/site-packages/pecan/extensions.py", line 67, in load_module
        extname = fullname.split(self.prefix)[1]
                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
    IndexError: list index out of range
```

**Comment by dmick** [comment]
@ryanpetrello any further thoughts on this, or should we pursue our own workarounds?

**Comment by ryanpetrello** [comment]
Hey Dan,

I haven't had a chance to look into this one more deeply yet.

**Comment by Thingee** [comment]
A quick fix I found is replacing:

```
from pecan.ext.notario import validate
```

with

```
from pecan_notario import validate
```

**Comment by alfredodeza** [comment]
I fully support going the simple route as well, +1 on @ryanpetrello based on @Thingee comment.

**Comment by ryanpetrello** [comment]
Just a note @Thingee @dmick if ya'll find that this works for you, let me know, and I may focus the effort here on just _removing_ `pecan.ext` in a future (`x.y`) release of pecan so that we can mark pecan as having 3.12 support.

**Comment by Thingee** [comment]
@ryanpetrello I can verify that Pecan works in Python 3.12 if we're not importing from pecan.ext.

There are warnings of a no longer maintained log color related package being used, and probably deprecation warnings that I saw. I can note them in a separate pecan issue if that'll be helpful.

**Comment by ryanpetrello** [comment]
Issues filed for deprecation warnings would be very helpful.

The color logging thing was intentionally removed (it's really only a nice-to-have for developers, and the library its based on is very old).

**Comment by dmick** [comment]
FWIW, I'm good moving to removing pecan.ext.  It doesn't seem like a big win in functionality to me anyway.
